# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaiPrincipal(object):
    def setupUi(self, MaiPrincipal):
        MaiPrincipal.setObjectName("MaiPrincipal")
        MaiPrincipal.resize(800, 600)
        MaiPrincipal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MaiPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.LblXesCli = QtWidgets.QLabel(self.centralwidget)
        self.LblXesCli.setGeometry(QtCore.QRect(290, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LblXesCli.setFont(font)
        self.LblXesCli.setAutoFillBackground(False)
        self.LblXesCli.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.955, stop:0.284091 rgba(170, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.LblXesCli.setAlignment(QtCore.Qt.AlignCenter)
        self.LblXesCli.setObjectName("LblXesCli")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 70, 691, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.LblDNI = QtWidgets.QLabel(self.centralwidget)
        self.LblDNI.setGeometry(QtCore.QRect(60, 110, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblDNI.setFont(font)
        self.LblDNI.setObjectName("LblDNI")
        self.EditDNI = QtWidgets.QLineEdit(self.centralwidget)
        self.EditDNI.setGeometry(QtCore.QRect(130, 110, 151, 20))
        self.EditDNI.setObjectName("EditDNI")
        self.LblApel = QtWidgets.QLabel(self.centralwidget)
        self.LblApel.setGeometry(QtCore.QRect(60, 150, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblApel.setFont(font)
        self.LblApel.setObjectName("LblApel")
        self.EditApel = QtWidgets.QLineEdit(self.centralwidget)
        self.EditApel.setGeometry(QtCore.QRect(130, 150, 241, 20))
        self.EditApel.setObjectName("EditApel")
        self.LblNombre = QtWidgets.QLabel(self.centralwidget)
        self.LblNombre.setGeometry(QtCore.QRect(430, 150, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblNombre.setFont(font)
        self.LblNombre.setObjectName("LblNombre")
        self.EditNom = QtWidgets.QLineEdit(self.centralwidget)
        self.EditNom.setGeometry(QtCore.QRect(490, 150, 241, 20))
        self.EditNom.setObjectName("EditNom")
        self.BtnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAceptar.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.BtnAceptar.setObjectName("BtnAceptar")
        self.BtnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSalir.setGeometry(QtCore.QRect(420, 260, 75, 23))
        self.BtnSalir.setObjectName("BtnSalir")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(50, 210, 701, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MaiPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MaiPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MaiPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MaiPrincipal)
        self.statusbar.setObjectName("statusbar")
        MaiPrincipal.setStatusBar(self.statusbar)

        self.retranslateUi(MaiPrincipal)
        QtCore.QMetaObject.connectSlotsByName(MaiPrincipal)

    def retranslateUi(self, MaiPrincipal):
        _translate = QtCore.QCoreApplication.translate
        MaiPrincipal.setWindowTitle(_translate("MaiPrincipal", "Proyecto 1"))
        self.LblXesCli.setText(_translate("MaiPrincipal", "XESTIÓN CLIENTES"))
        self.LblDNI.setText(_translate("MaiPrincipal", "DNI"))
        self.LblApel.setText(_translate("MaiPrincipal", "Apellidos"))
        self.LblNombre.setText(_translate("MaiPrincipal", "Nombre"))
        self.BtnAceptar.setText(_translate("MaiPrincipal", "Aceptar"))
        self.BtnSalir.setText(_translate("MaiPrincipal", "Salir"))
